// Custom Worker entrypoint: wraps the OpenNext-generated worker and adds a
// `scheduled` handler so Cloudflare's cron trigger (wrangler.jsonc → triggers.crons)
// drives the reminder heartbeat with zero external services.
// The .open-next/worker.js file is generated by `opennextjs-cloudflare build`.
import handler, { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";

export { DOQueueHandler, DOShardedTagCache, BucketCachePurge };

const worker = {
  fetch: handler.fetch,

  async scheduled(controller, env, ctx) {
    const key = env.CRON_SECRET ? `?key=${env.CRON_SECRET}` : "";
    const url = `${env.APP_URL || "https://cron.internal"}/api/cron/reminders${key}`;
    ctx.waitUntil(handler.fetch(new Request(url), env, ctx));
  },
};

export default worker;
